steps:
# 1. Initialize Terraform
- id: 'terraform import firewall'
  name: 'hashicorp/terraform:1.6.6'
  entrypoint: 'sh'
  args:
    - -c
    - |
      terraform -chdir=./infrastructure init


# 2. Generate a Plan (preview changes)
- id: 'terraform plan'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'terraform'
       #  Command arguments: terraform plan -out=tfplan -var="project_id=${PROJECT_ID}"
  args: ["-chdir=./infrastructure",'plan', '-out=tfplan']

# 3. Apply the Plan (deploy changes)
# This step is often conditional to prevent accidental deployments
# For a basic example, we include it here:
- id: 'terraform apply'
  name: 'hashicorp/terraform:latest'
  # Command arguments: terraform apply tfplan
  entrypoint: 'terraform'
  args: ["-chdir=./infrastructure",'apply', 'tfplan']

  # Set a timeout for the apply step to prevent indefinite runs
  timeout: '1200s' 

options:
  # This tells Cloud Build to send logs to Cloud Logging instead of a GCS bucket
  logging: CLOUD_LOGGING_ONLY